---
# Ref: aws s3 ls s3://amazon-eks/1.27.3/2023-06-30/bin/linux/amd64/
kubernetes_version: "{{ [version]| map('extract', versions, 'kubernetes_version') | last}}"
kubernetes_build_date: "{{ [version]| map('extract', versions, 'kubernetes_build_date') | last}}"
s3_binary_bucket: 'amazon-eks'
s3_binary_path: '{{ kubernetes_version }}/{{ kubernetes_build_date }}/bin/linux/{{ arch }}'

#### runc ####

runc_version: "{{ [version]| map('extract', versions, 'runc_version') | last}}"
runc_url: 'https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.{{ arch }}'
runc_checksum: 'sha256:https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.sha256sum'

#### containerd ####

containerd_version: "{{ [version]| map('extract', versions, 'containerd_version') | last}}"
containerd_archive: 'containerd-{{ containerd_version }}-linux-{{ arch }}.tar.gz'
containerd_url: 'https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/{{ containerd_archive }}'
containerd_checksum: 'sha256:https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/{{ containerd_archive }}.sha256sum'

#### nerdctl ####

nerdctl_version: "{{ [version]| map('extract', versions, 'nerdctl_version') | last}}"
nerdctl_archive: 'nerdctl-{{ nerdctl_version }}-linux-{{ arch }}.tar.gz'
nerdctl_url: 'https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_version }}/{{ nerdctl_archive }}'

#### CNI plugins ####

cni_plugins_version: "{{ [version]| map('extract', versions, 'cni_plugins_version') | last}}"
cni_plugins_archive: 'cni-plugins-linux-{{ arch }}-{{ cni_plugins_version }}.tgz'
cni_plugins_url: 'https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/{{ cni_plugins_archive }}'
cni_plugins_checksum: 'sha256:https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/{{ cni_plugins_archive }}.sha256'
