---
- name: Install prerequisites
  block:
    - name: Install dnf packages
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: present
      loop:
        - gcc
        - kernel-devel

#########################################################
# NVIDIA driver
#########################################################

- name: Install NVIDIA driver
  when: install_nvidia_driver|bool
  block:
    - name: Download NVIDIA driver installer {{ nvidia_driver_version }}
      ansible.builtin.get_url:
        url: '{{ nvidia_driver_url }}'
        dest: '/tmp/{{ nvidia_driver_executable }}'
      register: nvidia_driver_installer

    - name: Run NVIDIA driver installer
      ansible.builtin.shell: |
        sh {{ nvidia_driver_installer.dest }} -a -s --ui=none

#########################################################
# AWS EFA
#########################################################

- name: Install EFA
  when: install_efa|bool
  block:
    - name: Download EFA installer {{ efa_installer_version }}
      ansible.builtin.get_url:
        url: '{{ efa_installer_url }}'
        dest: '/tmp/{{ efa_installer_archive }}'
        checksum: '{{ efa_installer_checksum }}'
      register: efa_installer_archive

    - name: Extract EFA installer
      ansible.builtin.unarchive:
        src: '{{ efa_installer_archive.dest }}'
        dest: /tmp
        mode: 0755
        owner: root
        group: root
        remote_src: yes
      register: efa_installer

    - name: Run EFA installer
      ansible.builtin.shell:
        chdir: '{{ efa_installer.dest }}/aws-efa-installer'
        cmd: ./efa_installer.sh --enable-gdr --yes

    - name: Ensure ptrace protection is disabled
      ansible.posix.seboolean:
        name: deny_ptrace
        state: false
        persistent: true

#########################################################
# Clean-up
#########################################################

- name: Remove install prerequisites
  block:
    - name: Remove dnf packages
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: absent
      loop:
        - gcc
        - kernel-devel
        - rpmdevtools
        - rdma-core-devel
        - libfabric-aws-devel

### EFA w/ NCCL

# NCCL bandwidth test https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/troubleshooting.html#gpu-to-gpu-communication
# NCCL install docs https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html
# NCCL requires https://docs.nvidia.com/deeplearning/nccl/install-guide/index.html#softreq
#   - glibc 2.17 or higher
#   - CUDA 10.0 or higher

# Question - EFA docs have NCCL installed before EFA, is that required/recommended?
