---
- name: 'Provision EKS Amazon Linux 2023 Node'
  become: true
  hosts: default

  vars_files:
    # Generated map of versions that map Kubernetes version to artifact version
    - vars/versions.yaml

  roles:
    - eks
    - accelerate
    - harden

  tasks:
    - name: Stop containerd to ensure build logs are not leaked
      ansible.builtin.systemd:
        name: containerd
        state: stopped

    - name: Clean dnf/yum cache
      ansible.builtin.shell: |
        /usr/bin/dnf clean all
        /usr/bin/rm -rf /var/cache/dnf
        /usr/bin/yum clean all
        /usr/bin/rm -rf /var/cache/yum

    - name: Clean up files from build process
      ansible.builtin.file:
        path: '{{ item }}'
        state: absent
      loop:
        - /etc/hostname
        - /etc/machine-id
        - /etc/resolv.conf
        - /home/ec2-user/.ssh/authorized_keys
        - /root/.ssh/authorized_keys
        - /var/lib/cloud/data
        - /var/lib/cloud/instance
        - /var/lib/cloud/instances
        - /var/lib/cloud/sem
        - /var/log/amazon
        - /var/log/cloud-init-output.log
        - /var/log/cloud-init.log
        - /var/log/hawkey.log
        - /var/log/secure
        - /var/log/wtmp
        - /var/log/messages

    - name: Glob - Clean up files from build process
      ansible.builtin.shell: |
        /bin/rm -rf \
          /etc/ssh/ssh_host* \
          /var/lib/dhclient/* \
          /var/lib/dhcp/dhclient.* \
          /var/lib/dnf/* \
          /var/log/audit/* \
          /var/log/chrony/* \
          /var/log/dnf.* \
          /var/log/journal\* \
          /var/log/audit/*

    - name: Touch machine-id file
      ansible.builtin.file:
        path: /etc/machine-id
        state: touch
