#########################################################
# AWS EFA
#########################################################

- name: Download EFA installer {{ efa_installer_version }}
  ansible.builtin.get_url:
    url: '{{ efa_installer_url }}'
    dest: '/tmp/{{ efa_installer_archive }}'
    checksum: '{{ efa_installer_checksum }}'
  register: efa_installer_archive

- name: Extract EFA installer
  ansible.builtin.unarchive:
    src: '{{ efa_installer_archive.dest }}'
    dest: /tmp
    mode: 0755
    owner: root
    group: root
    remote_src: yes
  register: efa_installer

- name: Run EFA installer
  ansible.builtin.shell:
    chdir: '{{ efa_installer.dest }}/aws-efa-installer'
    # We only need the kernel module and rdma-core
    # OpenMPI and libfabric (along with NCCL, etc.) should
    # be provided in the application container
    cmd: ./efa_installer.sh --enable-gdr --minimal --yes

- name: Collect EFA installer version
  shell: echo "efa-installer,{{ efa_installer_version }}" >> /etc/eks/versions.csv

- name: Ensure ptrace protection is disabled
  ansible.posix.seboolean:
    name: deny_ptrace
    state: false
    persistent: true

- name: Clean-up packages
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: absent
    autoremove: true
  loop:
    - libstdc++-devel
    - rpmdevtools
    - rdma-core-devel
    - cmake
    - gcc
