---
- name: 'Provision EKS Amazon Linux 2023 Node'
  become: true
  hosts: default

  vars_files:
    - vars/accelerated.yaml
    # Generated map of versions that map Kubernetes version to artifact version
    - vars/versions.yaml

  roles:
    - eks

  tasks:
    #########################################################
    # Accelerated (GPU, EFA, etc.)
    #########################################################

    - name: Accelerated tasks
      when: install_nvidia|bool or install_neuron|bool or install_efa|bool
      block:
        - name: Install packages
          ansible.builtin.dnf:
            name: '{{ item }}'
            state: present
          loop:
            - gcc
            - kernel-devel

        - name: Run NVIDIA tasks
          when: install_nvidia|bool
          ansible.builtin.import_tasks:
            file: nvidia.yaml

        - name: Run Neuron tasks
          when: install_neuron|bool
          ansible.builtin.import_tasks:
            file: neuron.yaml

        - name: Run EFA tasks
          when: install_efa|bool
          ansible.builtin.import_tasks:
            file: efa.yaml

        - name: Clean-up packages
          ansible.builtin.dnf:
            name: '{{ item }}'
            state: absent
            autoremove: true
          loop:
            - gcc
            - kernel-devel
            - libstdc++-devel
            - rpmdevtools
            - rdma-core-devel
            - cmake

    #########################################################
    # CIS Level 1 and 2 baseline
    #########################################################

    - name: CIS Level 1 and 2 baseline
      when: harden_cis|bool
      become: true
      become_user: root
      block:
        - name: Install packages
          ansible.builtin.dnf:
            name: '{{ item }}'
            state: present
          loop:
            - acl
            - aide
            - firewalld
            - rsyslog

        - name: Amazon Linux 2023 CIS
          ansible.builtin.include_role:
            name: MindPointGroup.amazon2023_cis
            apply:
              become: true
          # https://github.com/ansible-lockdown/AMAZON2023-CIS/blob/devel/defaults/main.yml
          vars:
            # Ensure root password is set
            amzn2023cis_rule_4_6_6: false
            # https://github.com/ansible-lockdown/AMAZON2023-CIS/issues/14
            amzn2023cis_rule_1_2_1: false

    #########################################################
    # FIPs
    # https://docs.aws.amazon.com/linux/al2023/ug/fips-mode.html
    #########################################################

    - name: Enable FIPS Mode
      when: harden_fips|bool
      block:
        - name: Install packages
          ansible.builtin.dnf:
            name: '{{ item }}'
            state: present
          loop:
            - crypto-policies
            - crypto-policies-scripts

        - name: Enable FIPs mode
          ansible.builtin.shell: |
            fips-mode-setup --enable

    #########################################################
    # Clean-up
    #########################################################

    - name: Stop containerd to ensure build logs are not leaked
      ansible.builtin.systemd:
        name: containerd
        state: stopped

    - name: Clean-up tasks
      block:
        - name: Clean dnf/yum cache
          ansible.builtin.shell: |
            /usr/bin/dnf clean all
            /usr/bin/rm -rf /var/cache/dnf
            /usr/bin/yum clean all
            /usr/bin/rm -rf /var/cache/yum

        - name: Clean up files from build process
          ansible.builtin.file:
            path: '{{ item }}'
            state: absent
          loop:
            - /etc/hostname
            - /etc/machine-id
            - /etc/resolv.conf
            - /home/ec2-user/.ssh/authorized_keys
            - /root/.ssh/authorized_keys
            - /var/lib/cloud/data
            - /var/lib/cloud/instance
            - /var/lib/cloud/instances
            - /var/lib/cloud/sem
            - /var/log/amazon
            - /var/log/cloud-init-output.log
            - /var/log/cloud-init.log
            - /var/log/hawkey.log
            - /var/log/secure
            - /var/log/wtmp
            - /var/log/messages

        - name: Glob - Clean up files from build process
          ansible.builtin.shell: |
            /bin/rm -rf \
              /etc/ssh/ssh_host* \
              /var/lib/dhclient/* \
              /var/lib/dhcp/dhclient.* \
              /var/lib/dnf/* \
              /var/log/audit/* \
              /var/log/chrony/* \
              /var/log/dnf.* \
              /var/log/journal\* \
              /var/log/audit/*

        - name: Touch machine-id file
          ansible.builtin.file:
            path: /etc/machine-id
            state: touch
