#########################################################
# Neuron packages
#########################################################

- name: Add Neuron repo
  yum_repository:
    name: neuron
    description: Neuron YUM Repository
    baseurl: https://yum.repos.neuron.amazonaws.com/
    priority: 12
    keepcache: 0
    gpgcheck: true
    enabled: true
    gpgkey: https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

- name: Import Neuron GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB

- name: Install Neuron packages
  ansible.builtin.dnf:
    name: '{{ item }}'
    state: installed
    install_weak_deps: false
  loop:
    # - oci-add-hooks
    - aws-neuronx-dkms-2.*
    - aws-neuronx-tools-2.*
    # - aws-neuronx-oci-hook-2.*
