# Do not manually edit - this file is automatically generated with:
# cargo run --bin eksnode-gen update-ec2
#
# Contains array of EC2 instance types and their properties used by `eksnode`
# This is used to avoid AWS API calls when adding the node to the cluster

{{ #each instances as |instance| }}
{{ @key }}:
  default_vcpus: {{ instance.default_vcpus }}
  eni_maximum_pods: {{ instance.eni_maximum_pods }}
  gpu_manufacturer: {{ instance.gpu_manufacturer }}
  hypervisor: {{ instance.hypervisor }}
  instance_storage_supported: {{ instance.instance_storage_supported }}
  ipv4_addresses_per_interface: {{ instance.ipv4_addresses_per_interface }}
  maximum_network_interfaces: {{ instance.maximum_network_interfaces }}
{{ /each }}
