---
# This file is automatically generated by running `cargo run --bin eksnode-gen update-artifact-versions`
# The `kubernetes_` fields are managed by the `eksnode-gen` CLI, the rest are intended to be provided by users
#
# Look up the respective versions based on the `version` provided
versions: {
{{ #each versions as |version| }}
  '{{ @key }}': {
      # Generated by `cargo run --bin eksnode-gen update-artifact-versions`
      kubernetes_version: '{{ version.kubernetes_version }}',
      # Generated by `cargo run --bin eksnode-gen update-artifact-versions`
      kubernetes_build_date: '{{ version.kubernetes_build_date }}',
      runc_version: '{{ version.runc_version }}',
      containerd_version: '{{ version.containerd_version }}',
      cni_plugin_version: '{{ version.cni_plugin_version }}',
  },
{{ /each }}
}
