[package]
name = "eksnode"
version = "0.1.0"
authors = ["Bryant Biggs <bryantbiggs@gmail.com>"]
description = "A command line interface for interacting with EKS nodes"
documentation = "https://github.com/clowdhaus/eksnode"
homepage = "https://github.com/clowdhaus/eksnode"
repository = "https://github.com/clowdhaus/eksnode"
license = "Apache-2.0"
edition = "2021"
categories = [
  "command-line-utilities",
  "kubernetes",
]

default-run = "eksnode"

[[bin]]
name = "eksnode"
path = "src/main.rs"

[dependencies]
anstyle = "1.0.0"
anyhow = "1.0"
aws-config = "0.55"
aws-sdk-eks = "0.28"
aws-sdk-s3 = "0.28"
aws-types = "0.55"
base64 = "0.21.2"
clap = { version = "4.2", features = ["derive", "color", "unstable-styles"] }
clap-verbosity-flag = "2.0"
config = { version = "0.13", features = ["json", "yaml", "toml"] }
dns-lookup = "2.0"
http = "0.2"
ipnet = {version = "2.7", features = ["json"]}
num_cpus = "1.16"
phf = { version = "0.11", features = ["macros"] }
rand = "0.8"
regex = "1.8"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
tokio = { version = "1.23", features = ["full"] }
toml = "0.7"
tracing = {version = "0.1", features = ["log-always"] }
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2.0"
escargot = "0.5"
insta = "1.29"
rstest = "0.18"
tempfile = "3.6"
